### ISSUE TITLE
HTTP+JSON proxy endpoint : add support for non-struct return type

### ISSUE THREAD

**Issue by Raynos** [uber/zanzibar#223]
Currently the proxy code generation assumes either void or struct return type.

There is a [`string-return-type`](https://github.com/uber/zanzibar/tree/string-return-type) branch demonstrating this issue

If we use a string return type we get a panic like:

```
raynos at raynos-ThinkPad-T440p  
~/gocode/src/github.com/uber/zanzibar on string-return-type*
$ make generate
Compiled thriftrw : +1
Generating Go code from Thrift files
Generated structs : +2
Compiled easyjson : +2
Generating JSON Marshal/Unmarshal
Generated structs : +21
Generating module system components:
Generating     http   client bar                  in build/clients/bar              1/12
Generating tchannel   client baz                  in build/clients/baz              2/12
Generating     http   client contacts             in build/clients/contacts         3/12
Generating tchannel   client corge                in build/clients/corge            4/12
Generating     http   client google-now           in build/clients/google-now       5/12
Generating   custom   client quux                 in build/clients/quux             6/12
Generating     http endpoint bar                  in build/endpoints/bar            7/12
panic: interface conversion: compile.TypeSpec is *compile.StringSpec, not *compile.StructSpec

goroutine 1 [running]:
github.com/uber/zanzibar/codegen.(*MethodSpec).setTypeConverters(0xc420485600, 0xc42046aaf0, 0xc42041c0f0, 0x0, 0x0, 0xc4202bc1b0, 0x0, 0x0)
	/home/raynos/gocode/src/github.com/uber/zanzibar/codegen/method.go:790 +0x2fd
github.com/uber/zanzibar/codegen.(*ModuleSpec).SetDownstream(0xc4202bbf80, 0xc4205d1d30, 0x4, 0xc4205d1d36, 0xa, 0xc420350b40, 0xc4205d1e10, 0xa, 0x0, 0x0, ...)
	/home/raynos/gocode/src/github.com/uber/zanzibar/codegen/service.go:226 +0x725
github.com/uber/zanzibar/codegen.(*EndpointSpec).SetDownstream(0xc420435800, 0xc42031f1b8, 0x1, 0x1, 0xc4202bc1b0, 0x0, 0x0)
	/home/raynos/gocode/src/github.com/uber/zanzibar/codegen/gateway.go:820 +0x1d3
github.com/uber/zanzibar/codegen.(*EndpointGenerator).Generate(0xc42038f700, 0xc4203cf950, 0xc4203de87c, 0x4, 0xc4203bc1a8)
	/home/raynos/gocode/src/github.com/uber/zanzibar/codegen/module_system.go:605 +0x57b
github.com/uber/zanzibar/codegen.(*ModuleSystem).GenerateBuild(0xc42027fb00, 0xc420019100, 0x31, 0xc42001aa50, 0x49, 0xc42001ac30, 0x4f, 0x0, 0xc420019140, 0x40)
	/home/raynos/gocode/src/github.com/uber/zanzibar/codegen/module.go:911 +0x706
main.main()
	/home/raynos/gocode/src/github.com/uber/zanzibar/codegen/runner/runner.go:107 +0x926
exit status 2
Makefile:84: recipe for target 'generate' failed
make: *** [generate] Error 1
```

It looks like there is a TODO in the code for this edge case ( https://github.com/uber/zanzibar/blob/string-return-type/codegen/method.go#L782 ).

**Comment by Raynos** [comment]
This is done.
